clearvars
close all

load exp1data.mat

figure(1)
semilogy(Vb, IbQ1, 'r.', ...
     Vb, -negIeQ1, 'ro',...
     Vb, IbQ2, 'b.', ...
     Vb, -negIeQ2, 'bo', ...
     Vb, IbQ3, 'g.', ...
     Vb, -negIeQ3, 'go', ...
     Vb, IbQ4, 'c.', ...
     Vb, -negIeQ4, 'co');
title('V_b vs. I_b and I_e along with a theoretical fit')
xlabel('Voltage (V)')
ylabel('Current (A)')
legend('Q1 I_{C}', 'Q1 I_{B}',...
    'Q2 I_{C}', 'Q2 I_{B}', ...
    'Q3 I_{C}', 'Q3 I_{B}', ...
    'Q4 I_{C}', 'Q4 I_{B}')


